name: LinuxGccCMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CONAN_CMAKE_GENERATOR: Ninja

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11
        platform: x64

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Setup Ninja
      uses: ashutoshvarma/setup-ninja@v1.1
      with:
        dest: ${{github.workspace}}/.tools/ninja

    - name: Restore conan deps cache
      id: conan-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-gcc11-cxx20-conan-${{ hashFiles('conanfile.txt') }}

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=20 -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/conan_provider.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}

    - name: Save conan deps cache
      uses: actions/cache/save@v3
      with:
        path: ~/.conan2/p
        key: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}
