name: WinMsvcCMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CONAN_CMAKE_GENERATOR: Visual Studio 16 2019

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Restore conan deps cache
      id: conan-cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ~/.conan2/p
        key: ${{ runner.os }}-MSVS2019-cxx20-conan-${{ hashFiles('conanfile.txt') }}

    - name: Configure CMake
      run: cmake -G 'Visual Studio 16 2019' -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=20 "-DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=cmake/conan_provider.cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Save conan deps cache
      uses: actions/cache/save@v3
      with:
        path: ~/.conan2/p
        key: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
